# Execute the "targets" in this file with `make <target>` e.g. `make help`.
#
# You can also run multiple in sequence, e.g. `make clean lint test serve-coverage-report`
#
# See run.sh for more in-depth comments on what each target does.

build:
	bash run.sh build

clean:
	bash run.sh clean

help:
	bash run.sh help

install:
	bash run.sh install

lint:
	bash run.sh lint

lint-ci:
	bash run.sh lint:ci

publish-prod:
	bash run.sh publish:prod

publish-test:
	bash run.sh publish:test

release-prod:
	bash run.sh release:prod

release-test:
	bash run.sh release:test

serve-coverage-report:
	bash run.sh serve-coverage-report

test-ci:
	bash run.sh test:ci

test-quick:
	bash run.sh test:quick

test:
	bash run.sh run-tests

test-wheel-locally:
	bash run.sh test:wheel-locally

pulumi-up:
	bash run.sh pulumi:run up

pulumi-preview:
	bash run.sh pulumi:run preview

pulumi-destroy:
	bash run.sh pulumi:run destroy

.PHONY: build clean help install lint lint-ci publish-prod publish-test release-prod release-test serve-coverage-report test-ci test-quick test test-wheel-locally pulumi-up pulumi-preview pulumi-destroy
